// City alias map — maps common abbreviations / partial names to their canonical tokens

export const CITY_ALIASES = {
    "kl": ["kl", "kualalumpur", "kuala lumpur"],
    "kualalumpur": ["kl", "kualalumpur", "kuala lumpur"],
    "jb": ["jb", "johorbahru", "johor bahru", "jbsentral"],
    "johorbahru": ["jb", "johorbahru", "johor bahru", "jbsentral"],
    "jbsentral": ["jb", "johorbahru", "johor bahru", "jbsentral"],
    "klsentral": ["klsentral", "kl sentral", "kl", "kualalumpur"],
    "singapore": ["singapore", "sg", "changi"],
    "penang": ["penang", "pen", "georgetown", "butterworth"],
    "pen": ["penang", "pen", "georgetown"],
    "bali": ["bali", "dps", "ngurahrai", "denpasar"],
    "dps": ["bali", "dps", "denpasar"],
    "bangkok": ["bangkok", "bkk", "suvarnabhumi", "donmueang", "krungthep"],
    "bkk": ["bangkok", "bkk", "suvarnabhumi"],
    "tokyo": ["tokyo", "nrt", "hnd", "narita", "haneda", "japan"],
    "nrt": ["tokyo", "nrt", "narita"],
    "hnd": ["tokyo", "hnd", "haneda"],
    "osaka": ["osaka", "kix", "kansai"],
    "kix": ["osaka", "kix", "kansai"],
    "seoul": ["seoul", "icn", "incheon"],
    "icn": ["seoul", "icn", "incheon"],
    "hongkong": ["hongkong", "hkg", "hong kong"],
    "hkg": ["hongkong", "hkg", "hong kong"],
    "phuket": ["phuket", "hkt"],
    "hkt": ["phuket", "hkt"],
    "chiangmai": ["chiangmai", "chiang mai", "cnx"],
    "cnx": ["chiangmai", "chiang mai", "cnx"],
    "ipoh": ["ipoh"],
    "langkawi": ["langkawi", "lgk"],
    "lgk": ["langkawi", "lgk"],
    "kualalampur": ["kl", "kualalumpur"],
};