import { useState, useEffect, useMemo } from 'react'
// Lang 
import { useT, useCurrency } from '../../i18n/index.js'
// Components 
import { ContentPage } from '../../components/layouts';
import { FaLock } from "react-icons/fa6";

function PrivacyPage({ onBack, onNav }) {
    const t = useT();
    return (
        <ContentPage title={t("privacyHeroTitle")} subtitle={t("privacyHeroSub")} tag={<><FaLock /> {t("privacyTag")}</>} onBack={onBack} onNav={onNav} activePage="privacy">
            <div className="legal-updated">{t("lastUpdated")} 1 March 2026 · Effective: 1 April 2026</div>
            <div className="legal-toc">
                <p>{t("tableOfContents")}</p>
                <ol>{["Information We Collect", "How We Use Your Information", "Data Sharing", "Cookies & Tracking", "Data Retention", "Your Rights", "Security", "Children's Privacy", "Changes to This Policy", "Contact Us"].map((s, i) => <li key={i}>{s}</li>)}</ol>
            </div>
            {[
                ["1. Information We Collect", "We collect information you provide directly (name, email, phone, payment info, travel preferences), information generated by your use of Voyaqo (search history, bookings, device identifiers, IP addresses, location data where permitted), and information from third parties (airline booking systems, hotel reservation systems, identity verification providers)."],
                ["2. How We Use Your Information", "We use your data to process and manage bookings, personalise your experience and show relevant deals, send booking confirmations, travel alerts, and marketing communications (with your consent), improve our products through analytics and A/B testing, detect and prevent fraud and security threats, comply with legal obligations, and provide customer support."],
                ["3. Data Sharing", "We share your data with travel suppliers to fulfil your bookings (e.g., hotels, airlines, car rental companies), payment processors to handle transactions securely, analytics providers (Google Analytics, Mixpanel) under data processing agreements, marketing platforms (with anonymised or hashed identifiers), law enforcement or regulators when required by law, and no third parties for their own direct marketing without your explicit consent."],
                ["4. Cookies & Tracking", "We use essential cookies (required for the platform to function), performance cookies (analytics), functional cookies (preferences and saved searches), and targeting cookies (personalised ads, with consent). You can manage cookie preferences in your browser settings or through our cookie consent banner. Disabling non-essential cookies does not affect your ability to use Voyaqo."],
                ["5. Data Retention", "Booking records are retained for 7 years for tax and legal compliance. Account data is retained for 3 years after account closure. Marketing preferences are retained until you unsubscribe. Anonymised analytics data may be retained indefinitely."],
                ["6. Your Rights", "Under Malaysia's Personal Data Protection Act 2010 (PDPA) and applicable regional laws, you have the right to: access your personal data, correct inaccurate data, withdraw consent for marketing, request deletion of your account, object to certain processing, and data portability. To exercise these rights, email privacy@voyaqo.com with your request and a valid form of identification."],
                ["7. Security", "We use 256-bit TLS encryption for all data in transit, AES-256 encryption for sensitive data at rest, PCI-DSS Level 1 compliance for payment data, regular third-party penetration testing, and a dedicated security operations centre. In the event of a data breach affecting your personal data, we will notify you within 72 hours as required by law."],
                ["8. Children's Privacy", "Voyaqo is not directed at children under 13. We do not knowingly collect personal information from children. If you believe a child has provided us with personal data, please contact privacy@voyaqo.com immediately and we will delete the information promptly."],
                ["9. Changes to This Policy", "We may update this Privacy Policy from time to time. We will notify you of material changes by email or in-app notification at least 30 days before the change takes effect. Continued use of Voyaqo after the effective date constitutes acceptance of the updated policy."],
                ["10. Contact Us", "For privacy-related enquiries, contact our Data Protection Officer: DPO, Voyaqo Sdn. Bhd., 1 Jalan Sultan Ahmad Shah, George Town, 10050 Penang, Malaysia · privacy@voyaqo.com · +60 4-222 8895"],
            ].map(([h, t]) => <div key={h} className="cp-section"><h2>{h}</h2><p>{t}</p></div>)}
        </ContentPage>
    );
}

export default PrivacyPage
